### ISSUE TITLE
Simplifying the Stack

### ISSUE THREAD

**Issue by TerryE** [TerryE/docker-buildhub#3]
These issues are a bit like praying in that I doubt that anyone other then me will read these.  As I said in my proect README, one of the goals here is to build a simple manageable LAMP stack capable of run the Invision Community application suite on a pretty bare VPS with docker installed.  One of the key concerns that I want to mitigate is that of SysAdmin hand-over if I am forced by external circumstances to give up this role.  There are quite a few members of our forum that are in the IT industry and some have reasonable Linux skills, so I have any chance of handing this over, then the whole configuration needs to be as simple as possible.

For example, I did briefly investigated using the [S6 suite](https://skarnet.org/software/s6/) to allow to run multiple service daemons within a single contain, and this just wasn't worth all of the extra complexity and work involved.  It is just far simpler to leave all of the daemon control to docker.

A good correlate of simplicity is the number of lines of custom YAML, configs and scripts needed to run the stack. My focus should be to keep these as short as possible (not counting comments of course. 

-  The current upgrade involves a lot of messing around with mixed MySQL and PHP stacks whereas in steady state we only need one of each, so I can remove a lot of this complexity after the live upgrade.

-  The current approach build lots of containers.  If I move to volume mapping config hierarchies from the project folders in during the compose as `ro`  mounts, then I can pretty much get down to 2 containers:
    - The out-of-the box `mysql-8.0` container.
    - An extended `alpine:3.15` by adding `php8`, `apache2`, `redis` and `cron`.

-  I don't need `S6` because the `compose` would start 4 separate containers all based on the extended Alpine image each running `php8`, `apache2`, `redis` and `cron` respectively as the foreground PID 1 process.

**Comment by mikesharp01** [comment]
Looks like a good plan.

**Comment by mikesharp01** [comment]
During the upgrade process can you migrate data across the containers, I think you said there was a migration script as the db internal formats differ between the versions, or will you need to run the db update scripts in just the one?

**Comment by TerryE** [comment]
> I think you said there was a migration script as the db internal formats differ between the versions, or will you need to run the db update scripts in just the one?

The init script for `mysqld` does a version check as part of the startup sequence, so you can do the migration at MySQL 5.7, then bounce that stack to MySQL 8.0 and MySQL does the D/B upgrade seamlessly as part of the startup.  Clever, eh?

**Comment by TerryE** [comment]
@mikesharp01.  You might want to look at the current main code tree.  The Gen2 implementation  is a lot neater IMO.  Worth downloading the ZIP and cruising through by eyeball.
